dataset= 'Tusimple'
data_root= '/mnt/g/postgraduate_studyfile/Tusimple/train_set' # Need to be modified before running
epoch= 100
batch_size= 1
optimizer= 'SGD'
learning_rate= 0.000625     #######
weight_decay= 0.0001
momentum= 0.9
scheduler= 'multi'
steps= [50,75]
gamma= 0.1
warmup= 'linear'
warmup_iters= 100
backbone= '18'
griding_num= 100
use_aux= False
sim_loss_w= 0.0
shp_loss_w= 0.0
note= '' #用于给配置文件添加一些备注信息，可以帮助你区分不同的实验设置。
log_path= './log'  #用于保存日志和模型的工作目录的路径
finetune= None  #预训练模型的路径
resume= None  #训练过程中保存的模型的路径
test_model= ''  #一个训练好的模型的路径，如果你想要进行测试或可视化，可以设置这个参数。
test_work_dir= ''  #用于保存测试或可视化结果的工作目录的路径，如果你不指定，它会使用log_path参数的值
num_lanes= 4
var_loss_power= 2.0
auto_backup= True
num_row= 56
num_col= 41
train_width= 800
train_height= 320
num_cell_row= 100
num_cell_col= 100
mean_loss_w= 0.05
fc_norm= False
soft_loss= True
cls_loss_col_w= 1.0
cls_ext_col_w= 1.0
mean_loss_col_w= 0.05
eval_mode= 'normal'
crop_ratio = 0.8
